//Post foi feito pelo Prisma Studio


###
GET http://localhost:5555/user

###
GET http://localhost:5555/user/2

###
PUT http://localhost:5555/user/3
Content-Type: application/json

{
    "name": "Franciane",
    "email":"franciane@gmail.com"
}

###
DELETE http://localhost:5555/user/1
Content-Type: application/json